### ISSUE TITLE
Datenmodell

### ISSUE THREAD

**Issue by tbollmeyer** [Software-Projekt-2022/Verkehr#2]
Implementierung des Datenmodells als Grundlage für die Realisierung der User Stories.

Acceptance:
- [ ] Alle Entitäten implementiert
- [ ] Alle Beziehungen implementiert
- [x] Alle Optionalitäten & Kardinalitäten abgebildet

**Comment by Tezore** [comment]
MySQL Statements sind alle fertig, können noch nicht implementiert werden, da DB noch nicht online ist.
